name: Build whatjni
on:
  - pull_request
  - push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{matrix.arch}}-${{matrix.os}}-${{matrix.buildType}}
    runs-on: ${{matrix.environment}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows, linux]
        arch: [x64]
        buildType: [Release]
        javaVersion: [8]
        javaDistribution: [zulu]

        include:
          - os: windows
            arch: x64
            environment: windows-2019
            javaVersion: 8
            javaDistribution: zulu

          - os: linux
            arch: x64
            environment: ubuntu-20.04
            javaVersion: 8
            javaDistribution: zulu

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: ${{matrix.javaDistribution}}
          architecture: ${{matrix.arch}}

      - name: Gradle
        run: ./gradlew build

