name: Build whatjni
on:
  - pull_request
  - push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{matrix.arch}}-${{matrix.os}}-${{matrix.toolChain}}
    runs-on: ${{matrix.environment}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows, linux, mac]
        arch: [x64]
        javaVersion: [8]
        javaDistribution: [zulu]

        include:
          - os: windows
            arch: x64
            toolChain: msvc
            environment: windows-2019
            javaVersion: 8
            javaDistribution: zulu

          - os: linux
            arch: x64
            toolChain: gcc
            environment: ubuntu-20.04
            javaVersion: 8
            javaDistribution: zulu

          - os: linux
            arch: x64
            toolChain: clang
            environment: ubuntu-20.04
            javaVersion: 8
            javaDistribution: zulu

          - os: mac
            arch: x64
            toolChain: xcode
            environment: macos-10.15
            javaVersion: 8
            javaDistribution: zulu

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.javaVersion}}
          distribution: ${{matrix.javaDistribution}}
          architecture: ${{matrix.arch}}

      - name: JAVA_HOME diagnostics
        run: echo JAVA_HOME = $JAVA_HOME; ls -R $JAVA_HOME

      - name: Remove GCC
        run: sudo rm `which g++`; sudo rm `which gcc`
        if: ${{ matrix.os == 'linux' && matrix.toolChain != 'gcc' }}

      - name: Gradle
        run: ./gradlew build

