name: Build whatjni
on:
  - pull_request
  - push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{matrix.arch}} ${{matrix.os}} ${{matrix.toolChain}} JDK${{matrix.javaVersion}}/${{matrix.javaVM}}
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]
        arch: [x64]
        toolChain: [default]
        javaVersion: [16]
        javaVM: [hotspot]

        include:
          - os: ubuntu-20.04
            arch: x64
            toolChain: gcc
            javaVersion: 16
            javaVM: hotspot

          - os: ubuntu-18.04
            arch: x64
            toolChain: default
            javaVersion: 8
            javaVM: hotspot

          - os: windows-2019
            arch: x86
            toolChain: default
            javaVersion: 8
            javaVM: hotspot

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: ${{ matrix.javaVersion }}
          architecture: ${{ matrix.arch }}
          impl: ${{ matrix.javaVM }}

      - name: List JAVA_HOME
        run: ls -R $JAVA_HOME

      - name: Delete gcc tool chain
        run: sudo rm `which g++`; sudo rm `which gcc`
        if: ${{ startsWith(matrix.os, 'ubuntu') && matrix.toolChain == 'default' }}

      - name: Build
        run: ./gradlew runTest${{ env[matrix.os] }}${{ env[matrix.arch] }} linkRelease${{ env[matrix.os] }}${{ env[matrix.arch] }} --no-daemon
        env:
          windows-2019: Windows
          ubuntu-20.04: Linux
          macos-10.15: Macos
          x64: X86-64
          x86: X86
